Provide high-level taproot abstractions
ACINQ/bitcoin-kmp pull request #109
Opened 2024-01-12 09:17 UTC by t-bast

We provide helpers and better high-level abstractions for spending taproot outputs via either the key path or script path. This ensures that callers can't mess up which `SigVersion` they use, or forget to include the script leaf hash or merkle root depending on what they are spending.

The caller only needs to remember:

- the internal public key
- the script tree
- if they're using the script path, the ID of the script leaf they're using

That is information that they should always be able to keep around or recompute, and seems to be minimal.

NB: the two commits are somewhat independent and should be reviewed separately.

2024-01-15 18:26 UTC, sstone requested changes
Nice! Just a few comments and  nits.

2024-01-15 18:26 UTC, sstone commented on src/commonMain/kotlin/fr/acinq/bitcoin/Script.kt
> +        public fun build(internalPubKey: XonlyPublicKey, scriptTree: ScriptTree, spendingScript: ScriptTree.Leaf): ByteVector {
We should also allow users to build a control block even if they don't have the complete script tree but just its merkle root and a a merkle proof

2024-01-15 18:26 UTC, sstone commented on src/commonMain/kotlin/fr/acinq/bitcoin/Script.kt
> +    public fun pay2tr(internalKey: XonlyPublicKey, scripts: ScriptTree?): List<ScriptElt> {
We should also let user provide a merkle root instead of a script tree

2024-01-15 18:26 UTC, sstone commented on src/commonMain/kotlin/fr/acinq/bitcoin/ScriptTree.kt
> +                }
Nit: it could be refactored into:
```kotlin
    public fun merkleProof(leafId: Int): List<ByteVector32> {
        return when {
            this is Leaf && this.id == leafId -> {
                // We found our leaf: we can now walk up the tree to build the rest of the proof.
                listOf(this.hash())
            }
            this is Branch && this.left.merkleProof(leafId).isNotEmpty() -> {
                // Our target leaf is in that subtree: we add its sibling to the proof.
                this.left.merkleProof(leafId) + this.right.hash()
            }
            this is Branch && this.right.merkleProof(leafId).isNotEmpty() -> {
                // Our target leaf is in that subtree: we add its sibling to the proof.
                this.right.merkleProof(leafId) + this.left.hash()
            }
            else -> listOf()
        }
    }
```

2024-01-15 18:34 UTC, t-bast commented on src/commonMain/kotlin/fr/acinq/bitcoin/Script.kt
> +        public fun build(internalPubKey: XonlyPublicKey, scriptTree: ScriptTree, spendingScript: ScriptTree.Leaf): ByteVector {
Why do you think this is necessary? We only have use-cases where we know the whole script tree, so why bother with more complexity before we actually have use-cases for it?

2024-01-15 18:35 UTC, t-bast commented on src/commonMain/kotlin/fr/acinq/bitcoin/ScriptTree.kt
> +                }
True, but in the `Branch` case it means we need to compute `merkleProof(leafId)` twice, which isn't very satisfying...

2024-01-15 18:42 UTC, t-bast commented on src/commonMain/kotlin/fr/acinq/bitcoin/Script.kt
> +    public fun pay2tr(internalKey: XonlyPublicKey, scripts: ScriptTree?): List<ScriptElt> {
Done in https://github.com/ACINQ/bitcoin-kmp/pull/109/commits/e6fb4c054dc24846d2f80711d2696af4b8542262, this one makes sense when building outputs that you may not know how to spend, you may only have access to the merkle root indeed.

2024-01-15 19:10 UTC, sstone commented on src/commonMain/kotlin/fr/acinq/bitcoin/Script.kt
> +        public fun build(internalPubKey: XonlyPublicKey, scriptTree: ScriptTree, spendingScript: ScriptTree.Leaf): ByteVector {
Because one of the benefits of MAST is the ability to spend from a specific branch without knowing  the entire script tree but just what is necessary: the script root and a merkle proof (it is very useful to provide a high-level builder that takes a script tree and a specific leaf but as an addition, not a replacement).

2024-01-15 19:12 UTC, sstone commented on src/commonMain/kotlin/fr/acinq/bitcoin/ScriptTree.kt
> +                }
Yes but it's just micro-seconds here and the intent is more explicit

2024-01-16 09:32 UTC, t-bast commented on src/commonMain/kotlin/fr/acinq/bitcoin/ScriptTree.kt
> +                }
Fair enough, done in https://github.com/ACINQ/bitcoin-kmp/pull/109/commits/7495aff2d2500d52526c380e5dc1672d8c03777f

2024-01-16 09:35 UTC, t-bast commented on src/commonMain/kotlin/fr/acinq/bitcoin/Script.kt
> +        public fun build(internalPubKey: XonlyPublicKey, scriptTree: ScriptTree, spendingScript: ScriptTree.Leaf): ByteVector {
I agree that this is one of the theoretical use-case for MAST, but I'm pretty sure we won't use it in the short term, so I would have rather waited for a use-case to create better API for it. I've still added it in https://github.com/ACINQ/bitcoin-kmp/pull/109/commits/67589c651353f77be75d1592da293c76716b50a0, but I think it's a bad API that is too vague and too easy to misuse. Ideally users of the library should never be directly exposed to the control block, they should have helper functions that let them directly get `ScriptWitness` objects for their use-case.

2024-01-16 14:46 UTC, sstone commented on src/commonMain/kotlin/fr/acinq/bitcoin/ScriptTree.kt
> +                }
I've changed this in https://github.com/ACINQ/bitcoin-kmp/pull/111. I don't think that returning a list is the right API here

2024-01-16 15:38 UTC, t-bast commented on src/commonMain/kotlin/fr/acinq/bitcoin/ScriptTree.kt
> +                }
Good idea, the `merkleProof` function is only used to build control blocks, so we can directly return it in the format it expects (and the function is more elegant that way). I took the main change of your PR in https://github.com/ACINQ/bitcoin-kmp/pull/109/commits/5b679b6c6642fa6f6a3573369bf5aa309377d691, and omitted that seemed redundant.

2024-01-16 15:59 UTC, sstone commented on src/commonMain/kotlin/fr/acinq/bitcoin/Transaction.kt
> +            tapleaf: ByteVector32? = null,
Why split `executionData` into separate fields ? As much as possible, we try to match bitcoin core's implementation choices.

2024-01-16 16:08 UTC, t-bast commented on src/commonMain/kotlin/fr/acinq/bitcoin/Transaction.kt
> +            tapleaf: ByteVector32? = null,
Because it's not an `executionData` that is needed here, since it has at least one field of `executionData` that it doesn't use (`validationWeightLeft`). I really believe that `Script.ExecutionData` is an internal detail that should absolutely not be exposed to users of that library (and with that change, we don't expose it anymore). It is mostly used as a mutable variable during script validation, while hashing a transaction is used in other contexts as well.

Bitcoin Core isn't a library, so it doesn't care about the API it exposes on such functions, that's why it's okay-ish to reuse an object that doesn't completely fit in the context. But here this is a function we expose, so we should be more strict about what exactly we expose and avoid exposing unnecessary internal details.

2024-01-16 16:41 UTC, sstone commented on src/commonMain/kotlin/fr/acinq/bitcoin/Transaction.kt
> +            tapleaf: ByteVector32? = null,
Ok, but then `ExecutionData`'s visibility should be reduced (probably to `internal`)

2024-01-16 16:50 UTC, t-bast commented on src/commonMain/kotlin/fr/acinq/bitcoin/Transaction.kt
> +            tapleaf: ByteVector32? = null,
Yes that would be great! This isn't in the scope of this PR at all though, but several classes inside `Script` (and in other places as well) should be made `internal`, we expose way too much low-level details that callers don't need to know about.

2024-01-16 17:00 UTC, sstone approved these changes

2024-01-16 17:02 UTC, merged