Add test for large opSuccess tx
ACINQ/bitcoin-kmp pull request #76
Opened 2022-11-01 15:56 UTC by remyers

This PR creates a test for the huge `OP_SUCCESSx` tx created by [@brqgoo](https://twitter.com/brqgoo/status/1587397646125260802) in tx [73be398c4bdc43709db7398106609eea2a7841aaf3a4fa2000dc18184faa2a7e](https://blockstream.info/tx/73be398c4bdc43709db7398106609eea2a7841aaf3a4fa2000dc18184faa2a7e) and discussed in btcd issue [#1906]( https://github.com/btcsuite/btcd/issues/1906)

This transaction shouldn't be relayed, but once mined will be considered valid by bitcoin-kmp.

2022-11-02 13:21 UTC, sstone requested changes
Clever way of not adding nearly 500 Kb of data to our repo!

2022-11-02 13:21 UTC, sstone commented on src/commonTest/kotlin/fr/acinq/bitcoin/TaprootTestsCommon.kt
> +        val buffer = pre + ByteArray(500002) { 0 } + post
it should be possible to build this by reading the tx serialized without its witness and then populating the stack, it would make the tx structure and the use of OP_SUCCESS more explicit ?

2022-11-02 13:21 UTC, sstone commented on src/commonTest/kotlin/fr/acinq/bitcoin/TaprootTestsCommon.kt
> +        Transaction.correctlySpends(tx, parentTx, ScriptFlags.STANDARD_SCRIPT_VERIFY_FLAGS xor ScriptFlags.SCRIPT_VERIFY_DISCOURAGE_OP_SUCCESS)
there should be a comment explaining why we need to deactivate SCRIPT_VERIFY_DISCOURAGE_OP_SUCCESS

2022-11-03 15:00 UTC, remyers commented on src/commonTest/kotlin/fr/acinq/bitcoin/TaprootTestsCommon.kt
> +        Transaction.correctlySpends(tx, parentTx, ScriptFlags.STANDARD_SCRIPT_VERIFY_FLAGS xor ScriptFlags.SCRIPT_VERIFY_DISCOURAGE_OP_SUCCESS)
added comments in [d6281df](https://github.com/ACINQ/bitcoin-kmp/pull/76/commits/d6281dfee8ff285283028cca19faf860834572bd)

2022-11-03 15:01 UTC, remyers commented on src/commonTest/kotlin/fr/acinq/bitcoin/TaprootTestsCommon.kt
> +        val buffer = pre + ByteArray(500002) { 0 } + post
Great idea! I build the tx and populate the witness stack in [d6281df](https://github.com/ACINQ/bitcoin-kmp/pull/76/commits/d6281dfee8ff285283028cca19faf860834572bd).

2022-11-08 08:56 UTC, sstone approved these changes

2022-11-08 09:54 UTC, merged