Add a test with a 3Mb ordinals transaction
ACINQ/bitcoin-kmp pull request #83
Opened 2023-02-21 18:20 UTC by sstone

This tx highlighted a bug in how we encoded script size.

2023-02-22 08:03 UTC, t-bast commented on src/commonTest/kotlin/fr/acinq/bitcoin/BtcSerializerTestsCommon.kt
> +        }
Can you explain what you are testing here? I don't understand the `i - 1` and the `i *= 2uL`

2023-02-22 08:32 UTC, sstone commented on src/commonMain/kotlin/fr/acinq/bitcoin/BtcSerializer.kt
> +                input <= 65535uL -> {
Yes bitcoin is little endian and LN is big endian. With the proposed changes we match what bitcoin core does which is always a good thing :)

2023-02-22 08:34 UTC, sstone commented on src/commonTest/kotlin/fr/acinq/bitcoin/BtcSerializerTestsCommon.kt
> +        }
It's a basic test copied from bitcoin core that checks that we can read back what we wrote, using inputs that are supposed to be the trickiest to handle (`2^n` and `2^n - 1`).  We also have many implicit tests (through reference test vectors etc...) but none that triggered this bug.

2023-02-22 08:52 UTC, t-bast commented on src/commonTest/kotlin/fr/acinq/bitcoin/BtcSerializerTestsCommon.kt
> +        }
This really needs a comment, a test that readers don't understand isn't a good thing :)

2023-02-22 08:54 UTC, t-bast commented on src/commonMain/kotlin/fr/acinq/bitcoin/BtcSerializer.kt
> +                input <= 65535uL -> {
I find it a bit confusing that the implementation uses `<` for the first case but `<=` for the others to be honest...but if that matches the `bitcoind` implementation why not

2023-02-22 12:02 UTC, t-bast commented on src/commonTest/kotlin/fr/acinq/bitcoin/BtcSerializerTestsCommon.kt
> +    }
I find it much clearer that way, what do you think:

```suggestion
// test that we can read back what we wrote using values that are trickier to encode (2^n - 1, 2^n, 2^n + 1)
        for (i in 0..31) {
            val output = ByteArrayOutput()
            val v = (1 shl i).toULong()
            BtcSerializer.writeVarint(v - 1UL, output)
            BtcSerializer.writeVarint(v, output)
            BtcSerializer.writeVarint(v + 1UL, output)
            val input = ByteArrayInput(output.toByteArray())
            assertEquals(BtcSerializer.varint(input), v - 1UL)
            assertEquals(BtcSerializer.varint(input), v)
            assertEquals(BtcSerializer.varint(input), v + 1UL)
        }
```

2023-02-22 13:38 UTC, t-bast approved these changes
LGTM!

2023-02-23 14:30 UTC, remyers requested changes
I compared to the core code and tested with and without the fixes to double check the tests catch any issues. I only had a question and found an issue with the test.

2023-02-23 17:56 UTC, sstone commented on src/commonTest/kotlin/fr/acinq/bitcoin/BtcSerializerTestsCommon.kt
> +        for (i in 0..31) {
yes `compactSize` is more widely used than `varint`. You're right I will update the test.

2023-02-23 18:06 UTC, t-bast approved these changes

2023-02-23 18:07 UTC, sstone commented on src/commonTest/kotlin/fr/acinq/bitcoin/BtcSerializerTestsCommon.kt
> +        for (i in 0..31) {
done in https://github.com/ACINQ/bitcoin-kmp/pull/83/commits/6bfdb03164b36581392511c89a2f9108e88b529f

2023-02-24 07:47 UTC, remyers approved these changes
Looks good! 

small nit: 

`val v = (1uL shl i)`  uses lower case `uL`, a few lines down it's an uppercase `UL` and a few lines above it's `uL`. Both are valid, Kotlin docs say "uL and UL explicitly tag literal as unsigned long"

2023-02-24 15:01 UTC, sstone commented
> small nit:
> 
> `val v = (1uL shl i)` uses lower case `uL`, a few lines down it's an uppercase `UL` and a few lines above it's `uL`. Both are valid, Kotlin docs say "uL and UL explicitly tag literal as unsigned long"

Ah now I have to fix :)

2023-02-27 12:49 UTC, merged