Fix OP_PUSHDATA encoding
ACINQ/bitcoin-kmp pull request #85
Opened 2023-02-28 16:21 UTC by sstone

There was an error encoding pushes of 255 bytes

2023-03-01 16:04 UTC, remyers requested changes
Seems like the edge cases are handled now. The subtlety with non-minimal encoding tests took me a bit to wrap my head around. 

I have a few questions about the OP_PUSHDATAs < `0x4c` cases and adding exceptions generally. 

I also confirmed the new puzzle by trying with/without the changes you made to `Script.write` and examined the script from the original txs that failed.

2023-03-02 13:27 UTC, sstone commented on src/commonMain/kotlin/fr/acinq/bitcoin/Script.kt
> +                            require(head.data.size() <= 0x4c)
Yes, this check was wrong it should be  ` require(head.data.size() == head.code)`, fixed in  https://github.com/ACINQ/bitcoin-kmp/pull/85/commits/c2c9115babf500de12c1279811dcc05a3bcd2893

2023-03-02 13:31 UTC, sstone commented on src/commonMain/kotlin/fr/acinq/bitcoin/Script.kt
> +                        else -> error("invalid OP_PUSHADATA opcode ${head.code}")
it will be done implicitly now that we check that `head.data.size() == head.code`

2023-03-02 13:32 UTC, sstone commented on src/commonTest/kotlin/fr/acinq/bitcoin/BtcSerializerTestsCommon.kt
> +            OP_PUSHDATA(ByteArray(0x01) { 0x01 }, 0x4c), // non-minimal encoding
Yes see above

2023-03-02 13:36 UTC, sstone commented on src/commonTest/kotlin/fr/acinq/bitcoin/BtcSerializerTestsCommon.kt
>  }
It should always be safe to throw an exception here when data is invalid (i.e. does not match the specs), I've added a few additional tests.

2023-03-02 13:42 UTC, remyers approved these changes
LGTM!

2023-03-02 13:51 UTC, merged