All a segwit PSBT input to be updated with a non-segwit utxo
ACINQ/bitcoin-kmp pull request #86
Opened 2023-03-08 15:14 UTC by sstone

Non-segwit utxos incude the full tx being spent and not just its output.
This can be used to detect "fee attacks" where the segwit utxo's output amount does  not match the amount that is actually spent.

2023-03-09 15:59 UTC, remyers requested changes
Changes look good, but I found an issue when I tried to serialize/deserialize the psbt with invalid nonWitness input data.

You should also add tests for the `derivationPaths` being properly updated.

2023-03-09 15:59 UTC, remyers commented on src/commonTest/kotlin/fr/acinq/bitcoin/psbt/PsbtTestsCommon.kt
> +    }
I tried to test that an invalid psbt would throw the appropriate error when deserialized, but it instead fails to deserialize the nonWitnessUtxo, any ideas why?
 
```
        // a psbt with mismatched nonWitnessUtxo and witnessUtxo should not deserialize
        assertEquals(Psbt.read(Psbt.write(psbt3)), Either.Left(ParseFailure.InvalidTxInput("non-witness utxo does not match psbt outpoint")))
```

2023-03-09 17:42 UTC, sstone commented on src/commonTest/kotlin/fr/acinq/bitcoin/psbt/PsbtTestsCommon.kt
> +    }
it seems that Psbt.write(psbt3) produces an invalid ouput, I don't know why yet

2023-03-09 18:21 UTC, sstone commented on src/commonTest/kotlin/fr/acinq/bitcoin/psbt/PsbtTestsCommon.kt
> +    }
fixed in https://github.com/ACINQ/bitcoin-kmp/pull/86/commits/661a6765e140cf014dfb6065390bd064e5c4b056
(the non-witness utxo was a tx without inputs that could not be de-serialised, I've added dummy input)

2023-03-10 07:43 UTC, remyers approved these changes
LGTM! these changes will help inform review of [PR #2345](https://github.com/ACINQ/eclair/pull/2345/files)

2023-03-10 08:18 UTC, merged

2023-03-13 08:46 UTC, t-bast commented on src/commonMain/kotlin/fr/acinq/bitcoin/psbt/Psbt.kt
> +            )
This is very confusing now, we allow mixing segwit and non-segwit functions, which is a terrible API for callers...if we decide we only want to support scenarios where the full previous transaction is always provided, we should make deeper changes to make it much clearer for callers (and that would greatly simplify the code as well).

2023-03-13 09:34 UTC, sstone commented on src/commonMain/kotlin/fr/acinq/bitcoin/psbt/Psbt.kt
> +            )
Yes naming is a bit confusing but the change here is very simple and matches what bitcoin core does: they  add a `non_witness_utxo` field to all PSBT segwit v0 inputs for the same reason: to protect against fee attacks (see https://github.com/bitcoin/bitcoin/blob/v24.0.1/src/wallet/wallet.cpp#L2059).